import type { APIPlayerDuelsStats } from "@stats-types/duels.js";
import { DuelsBedFightStats } from "./BedFight/BedFight.js";
import { DuelsBedFightDoublesStats } from "./BedFight/Doubles.js";
import { DuelsBedFightSoloStats } from "./BedFight/Solo.js";
import { DuelsBedRushStats } from "./BedRush/BedRush.js";
import { DuelsBedRushSoloStats } from "./BedRush/Solo.js";
import { DuelsBoxingStats } from "./Boxing/Boxing.js";
import { DuelsBoxingSoloStats } from "./Boxing/Solo.js";
import { DuelsBridge1v1v1v1Stats } from "./Bridge/1v1v1v1.js";
import { DuelsBridgeStats } from "./Bridge/Bridge.js";
import { DuelsBridgeDoublesStats } from "./Bridge/Doubles.js";
import { DuelsBridgeFourStats } from "./Bridge/Four.js";
import { DuelsBridgeSoloStats } from "./Bridge/Solo.js";
import { DuelsBridgeThreeStats } from "./Bridge/Three.js";
import { DuelsFireballFightDoublesStats } from "./FireballFight/Doubles.js";
import { DuelsFireballFightStats } from "./FireballFight/FireballFight.js";
import { DuelsFireballFightSoloStats } from "./FireballFight/Solo.js";
import { DuelsGappleStats } from "./Gapple/Gapple.js";
import { DuelsGappleSoloStats } from "./Gapple/Solo.js";
import { DuelsGladiatorDoublesStats } from "./Gladiator/Doubles.js";
import { DuelsGladiatorStats } from "./Gladiator/Gladiator.js";
import { DuelsGladiatorSoloStats } from "./Gladiator/Solo.js";
import { DuelsHGSimDoublesStats } from "./HGSim/Doubles.js";
import { DuelsHGSimStats } from "./HGSim/HGSimulator.js";
import { DuelsHGSimSoloStats } from "./HGSim/Solo.js";
import { DuelsLavaStats } from "./Lava/Lava.js";
import { DuelsLavaSoloStats } from "./Lava/Solo.js";
import { DuelsNoDebuffDoublesStats } from "./NoDebuff/Doubles.js";
import { DuelsNoDebuffStats } from "./NoDebuff/NoDebuff.js";
import { DuelsNoDebuffSoloStats } from "./NoDebuff/Solo.js";
import { DuelsPearlFightStats } from "./PearlFight/PearlFight.js";
import { DuelsPearlFightSoloStats } from "./PearlFight/Solo.js";
import { DuelsSoupDoublesStats } from "./Soup/Doubles.js";
import { DuelsSoupSoloStats } from "./Soup/Solo.js";
import { DuelsSoupStats } from "./Soup/Soup.js";
import { DuelsSumoSoloStats } from "./Sumo/Solo.js";
import { DuelsSumoStats } from "./Sumo/Sumo.js";
import { DuelsUHCDoublesStats } from "./UHC/Doubles.js";
import { DuelsUHCFourStats } from "./UHC/Four.js";
import { DuelsUHCSoloStats } from "./UHC/Solo.js";
import { DuelsUHCStats } from "./UHC/UHC.js";

export class DuelsStats {
  public bedFight: DuelsBedFightStats;
  public bedFightDoubles: DuelsBedFightDoublesStats;
  public bedFightSolo: DuelsBedFightSoloStats;
  public bedRush: DuelsBedRushStats;
  public bedRushSolo: DuelsBedRushSoloStats;
  public boxing: DuelsBoxingStats;
  public boxingSolo: DuelsBoxingSoloStats;
  public bridge: DuelsBridgeStats;
  public bridge1v1v1v1: DuelsBridge1v1v1v1Stats;
  public bridgeSolo: DuelsBridgeSoloStats;
  public bridgeDoubles: DuelsBridgeDoublesStats;
  public bridgeThree: DuelsBridgeThreeStats;
  public bridgeFour: DuelsBridgeFourStats;
  public fireballFight: DuelsFireballFightStats;
  public fireballFightDoubles: DuelsFireballFightDoublesStats;
  public fireballFightSolo: DuelsFireballFightSoloStats;
  public gapple: DuelsGappleStats;
  public gappleSolo: DuelsGappleSoloStats;
  public gladiator: DuelsGladiatorStats;
  public gladiatorDoubles: DuelsGladiatorDoublesStats;
  public gladiatorSolo: DuelsGladiatorSoloStats;
  public hgSim: DuelsHGSimStats;
  public hgSimDoubles: DuelsHGSimDoublesStats;
  public hgSimSolo: DuelsHGSimSoloStats;
  public lava: DuelsLavaStats;
  public lavaSolo: DuelsLavaSoloStats;
  public noDebuff: DuelsNoDebuffStats;
  public noDebuffDoubles: DuelsNoDebuffDoublesStats;
  public noDebuffSolo: DuelsNoDebuffSoloStats;
  public pearlFight: DuelsPearlFightStats;
  public pearlFightSolo: DuelsPearlFightSoloStats;
  public soup: DuelsSoupStats;
  public soupDoubles: DuelsSoupDoublesStats;
  public soupSolo: DuelsSoupSoloStats;
  public sumo: DuelsSumoStats;
  public sumoSolo: DuelsSumoSoloStats;
  public uhc: DuelsUHCStats;
  public uhcDoubles: DuelsUHCDoublesStats;
  public uhcSolo: DuelsUHCSoloStats;
  public uhcFour: DuelsUHCFourStats;

  constructor(data: Partial<APIPlayerDuelsStats> = {}) {
    this.bedFight = new DuelsBedFightStats(data);
    this.bedFightDoubles = new DuelsBedFightDoublesStats(data);
    this.bedFightSolo = new DuelsBedFightSoloStats(data);
    this.bedRush = new DuelsBedRushStats(data);
    this.bedRushSolo = new DuelsBedRushSoloStats(data);
    this.boxing = new DuelsBoxingStats(data);
    this.boxingSolo = new DuelsBoxingSoloStats(data);
    this.bridge = new DuelsBridgeStats(data);
    this.bridge1v1v1v1 = new DuelsBridge1v1v1v1Stats(data);
    this.bridgeSolo = new DuelsBridgeSoloStats(data);
    this.bridgeDoubles = new DuelsBridgeDoublesStats(data);
    this.bridgeThree = new DuelsBridgeThreeStats(data);
    this.bridgeFour = new DuelsBridgeFourStats(data);
    this.fireballFight = new DuelsFireballFightStats(data);
    this.fireballFightDoubles = new DuelsFireballFightDoublesStats(data);
    this.fireballFightSolo = new DuelsFireballFightSoloStats(data);
    this.gapple = new DuelsGappleStats(data);
    this.gappleSolo = new DuelsGappleSoloStats(data);
    this.gladiator = new DuelsGladiatorStats(data);
    this.gladiatorDoubles = new DuelsGladiatorDoublesStats(data);
    this.gladiatorSolo = new DuelsGladiatorSoloStats(data);
    this.hgSim = new DuelsHGSimStats(data);
    this.hgSimDoubles = new DuelsHGSimDoublesStats(data);
    this.hgSimSolo = new DuelsHGSimSoloStats(data);
    this.lava = new DuelsLavaStats(data);
    this.lavaSolo = new DuelsLavaSoloStats(data);
    this.noDebuff = new DuelsNoDebuffStats(data);
    this.noDebuffDoubles = new DuelsNoDebuffDoublesStats(data);
    this.noDebuffSolo = new DuelsNoDebuffSoloStats(data);
    this.pearlFight = new DuelsPearlFightStats(data);
    this.pearlFightSolo = new DuelsPearlFightSoloStats(data);
    this.soup = new DuelsSoupStats(data);
    this.soupDoubles = new DuelsSoupDoublesStats(data);
    this.soupSolo = new DuelsSoupSoloStats(data);
    this.sumo = new DuelsSumoStats(data);
    this.sumoSolo = new DuelsSumoSoloStats(data);
    this.uhc = new DuelsUHCStats(data);
    this.uhcDoubles = new DuelsUHCDoublesStats(data);
    this.uhcSolo = new DuelsUHCSoloStats(data);
    this.uhcFour = new DuelsUHCFourStats(data);
  }
}
