import type { APIPlayerBedWarsStats } from "@stats-types/bedwars";
import { DefaultGameLevelBadgeColorType, LevelBadge } from "../LevelBadge.js";
import { BedWars1v1Stats } from "./Modes/1v1.js";
import { BedWars2v2Stats } from "./Modes/2v2.js";
import { BedWars3v3Stats } from "./Modes/3v3.js";
import { BedWars3v3v3v3Stats } from "./Modes/3v3v3v3.js";
import { BedWars4sStats } from "./Modes/4s.js";
import { BedWars4v4Stats } from "./Modes/4v4.js";
import { BedWars4v4v4v4Stats } from "./Modes/4v4v4v4.js";
import { BedWarsBoostDoublesStats } from "./Modes/BoostDoubles.js";
import { BedWarsBoostSoloStats } from "./Modes/BoostSolo.js";
import { BedWarsChampionsStats } from "./Modes/Champions.js";
import { BedWarsClassicSoloStats } from "./Modes/ClassicSolo.js";
import { BedWarsDoublesStats } from "./Modes/Doubles.js";
import { BedWarsHardcore4v4v4v4Stats } from "./Modes/Hardcore4v4v4v4.js";
import { BedWarsHardcoreSoloStats } from "./Modes/HardcoreSolo.js";
import { BedWarsHookDoublesStats } from "./Modes/HookDoubles.js";
import { BedWarsHookSoloStats } from "./Modes/HookSolo.js";
import { BedWarsInfectionDoublesStats } from "./Modes/InfectionDoubles.js";
import { BedWarsInfectionSoloStats } from "./Modes/InfectionSolo.js";
import { BedWarsMegaStats } from "./Modes/Mega.js";
import { BedWarsSoloStats } from "./Modes/Solo.js";

export class BedWarsStats {
  public "1v1": BedWars1v1Stats;
  public "2v2": BedWars2v2Stats;
  public "3v3": BedWars3v3Stats;
  public "3v3v3v3": BedWars3v3v3v3Stats;
  public "4s": BedWars4sStats;
  public "4v4": BedWars4v4Stats;
  public "4v4v4v4": BedWars4v4v4v4Stats;
  public assists: number;
  public bedsBroken: number;
  public bedsLost: number;
  public boostDoubles: BedWarsBoostDoublesStats;
  public boostSolo: BedWarsBoostSoloStats;
  public champions: BedWarsChampionsStats;
  public classicSolo: BedWarsClassicSoloStats;
  public dailyBedsBroken: number;
  public dailyFinalKills: number;
  public dailyKills: number;
  public dailyLevel: number;
  public dailyWins: number;
  public dailyWinstreak: number;
  public dailyXp: number;
  public deaths: number;
  public doubles: BedWarsDoublesStats;
  public finalAssists: number;
  public finalDeaths: number;
  public finalKills: number;
  public fkdr: number;
  public gamesPlayed: number;
  public hardcore4v4v4v4: BedWarsHardcore4v4v4v4Stats;
  public hardcoreSolo: BedWarsHardcoreSoloStats;
  public hookDoubles: BedWarsHookDoublesStats;
  public hookSolo: BedWarsHookSoloStats;
  public infectionDoubles: BedWarsInfectionDoublesStats;
  public infectionSolo: BedWarsInfectionSoloStats;
  public kills: number;
  public level: number;
  public levelBadge: LevelBadge;
  public losses: number;
  public maxWinstreak: number;
  public mega: BedWarsMegaStats;
  public monthlyBedsBroken: number;
  public monthlyFinalKills: number;
  public monthlyKills: number;
  public monthlyLevel: number;
  public monthlyWins: number;
  public monthlyWinstreak: number;
  public monthlyXp: number;
  public solo: BedWarsSoloStats;
  public wins: number;
  public winstreak: number;
  public weeklyBedsBroken: number;
  public weeklyFinalKills: number;
  public weeklyKills: number;
  public weeklyLevel: number;
  public weeklyWins: number;
  public weeklyWinstreak: number;
  public weeklyXp: number;
  public xp: number;

  constructor(data: Partial<APIPlayerBedWarsStats> = {}) {
    this.assists = data.assists ?? 0;
    this.bedsBroken = data.beds_broken ?? 0;
    this.dailyBedsBroken = data.beds_broken_daily ?? 0;
    this.weeklyBedsBroken = data.beds_broken_weekly ?? 0;
    this.monthlyBedsBroken = data.beds_broken_monthly ?? 0;
    this.bedsLost = data.beds_lost ?? 0;
    this.deaths = data.deaths ?? 0;
    this.finalAssists = data.final_assists ?? 0;
    this.finalDeaths = data.final_deaths ?? 0;
    this.finalKills = data.final_kills ?? 0;
    this.dailyFinalKills = data.final_kills_daily ?? 0;
    this.weeklyFinalKills = data.final_kills_weekly ?? 0;
    this.monthlyFinalKills = data.final_kills_monthly ?? 0;
    this.fkdr = data.fkdr ?? 0;
    this.gamesPlayed = data.games_played ?? 0;
    this.kills = data.kills ?? 0;
    this.dailyKills = data.kills_daily ?? 0;
    this.weeklyKills = data.kills_weekly ?? 0;
    this.monthlyKills = data.kills_monthly ?? 0;
    this.level = data.level ?? 0;
    this.levelBadge = new LevelBadge(
      data.level_badge ?? DefaultGameLevelBadgeColorType,
    );
    this.dailyLevel = data.level_daily ?? 0;
    this.weeklyLevel = data.level_weekly ?? 0;
    this.monthlyLevel = data.level_monthly ?? 0;
    this.losses = data.losses ?? 0;
    this.maxWinstreak = data.max_winstreak ?? 0;
    this.wins = data.wins ?? 0;
    this.dailyWins = data.wins_daily ?? 0;
    this.weeklyWins = data.wins_weekly ?? 0;
    this.monthlyWins = data.wins_monthly ?? 0;
    this.winstreak = data.winstreak ?? 0;
    this.dailyWinstreak = data.winstreak_daily ?? 0;
    this.weeklyWinstreak = data.winstreak_weekly ?? 0;
    this.monthlyWinstreak = data.winstreak_monthly ?? 0;
    this.xp = data.xp ?? 0;
    this.dailyXp = data.xp_daily ?? 0;
    this.weeklyXp = data.xp_weekly ?? 0;
    this.monthlyXp = data.xp_monthly ?? 0;

    this["1v1"] = new BedWars1v1Stats(data);
    this["2v2"] = new BedWars2v2Stats(data);
    this["3v3"] = new BedWars3v3Stats(data);
    this["3v3v3v3"] = new BedWars3v3v3v3Stats(data);
    this["4s"] = new BedWars4sStats(data);
    this["4v4"] = new BedWars4v4Stats(data);
    this["4v4v4v4"] = new BedWars4v4v4v4Stats(data);

    this.boostDoubles = new BedWarsBoostDoublesStats(data);
    this.boostSolo = new BedWarsBoostSoloStats(data);
    this.champions = new BedWarsChampionsStats(data);
    this.classicSolo = new BedWarsClassicSoloStats(data);
    this.doubles = new BedWarsDoublesStats(data);
    this.hardcore4v4v4v4 = new BedWarsHardcore4v4v4v4Stats(data);
    this.hardcoreSolo = new BedWarsHardcoreSoloStats(data);
    this.hookDoubles = new BedWarsHookDoublesStats(data);
    this.hookSolo = new BedWarsHookSoloStats(data);
    this.infectionDoubles = new BedWarsInfectionDoublesStats(data);
    this.infectionSolo = new BedWarsInfectionSoloStats(data);
    this.mega = new BedWarsMegaStats(data);
    this.solo = new BedWarsSoloStats(data);
  }
}
