import type { APIPlayerBedWarsStats } from "@stats-types/bedwars";
import { DefaultGameLevelBadgeColorType, LevelBadge } from "../LevelBadge.js";
import { BedWars1v1Stats } from "./Modes/1v1.js";
import { BedWars2v2Stats } from "./Modes/2v2.js";
import { BedWars3v3Stats } from "./Modes/3v3.js";
import { BedWars3v3v3v3Stats } from "./Modes/3v3v3v3.js";
import { BedWars4sStats } from "./Modes/4s.js";
import { BedWars4v4Stats } from "./Modes/4v4.js";
import { BedWars4v4v4v4Stats } from "./Modes/4v4v4v4.js";
import { BedWarsBoostDoublesStats } from "./Modes/BoostDoubles.js";
import { BedWarsBoostSoloStats } from "./Modes/BoostSolo.js";
import { BedWarsChampionsStats } from "./Modes/Champions.js";
import { BedWarsClassicSoloStats } from "./Modes/ClassicSolo.js";
import { BedWarsDoublesStats } from "./Modes/Doubles.js";
import { BedWarsHardcore4v4v4v4Stats } from "./Modes/Hardcore4v4v4v4.js";
import { BedWarsHardcoreSoloStats } from "./Modes/HardcoreSolo.js";
import { BedWarsHookDoublesStats } from "./Modes/HookDoubles.js";
import { BedWarsHookSoloStats } from "./Modes/HookSolo.js";
import { BedWarsInfectionDoublesStats } from "./Modes/InfectionDoubles.js";
import { BedWarsInfectionSoloStats } from "./Modes/InfectionSolo.js";
import { BedWarsMegaStats } from "./Modes/Mega.js";
import { BedWarsSoloStats } from "./Modes/Solo.js";

export interface BedWarsStats {
  "1v1": BedWars1v1Stats;
  "2v2": BedWars2v2Stats;
  "3v3": BedWars3v3Stats;
  "3v3v3v3": BedWars3v3v3v3Stats;
  "4s": BedWars4sStats;
  "4v4": BedWars4v4Stats;
  "4v4v4v4": BedWars4v4v4v4Stats;
  assists: number;
  bedsBroken: number;
  bedsLost: number;
  boostDoubles: BedWarsBoostDoublesStats;
  boostSolo: BedWarsBoostSoloStats;
  champions: BedWarsChampionsStats;
  classicSolo: BedWarsClassicSoloStats;
  dailyBedsBroken: number;
  dailyFinalKills: number;
  dailyKills: number;
  dailyLevel: number;
  dailyWins: number;
  dailyWinstreak: number;
  dailyXp: number;
  deaths: number;
  doubles: BedWarsDoublesStats;
  finalAssists: number;
  finalDeaths: number;
  finalKills: number;
  fkdr: number;
  gamesPlayed: number;
  hardcore4v4v4v4: BedWarsHardcore4v4v4v4Stats;
  hardcoreSolo: BedWarsHardcoreSoloStats;
  hookDoubles: BedWarsHookDoublesStats;
  hookSolo: BedWarsHookSoloStats;
  infectionDoubles: BedWarsInfectionDoublesStats;
  infectionSolo: BedWarsInfectionSoloStats;
  kills: number;
  level: number;
  levelBadge: LevelBadge;
  losses: number;
  maxWinstreak: number;
  mega: BedWarsMegaStats;
  monthlyBedsBroken: number;
  monthlyFinalKills: number;
  monthlyKills: number;
  monthlyLevel: number;
  monthlyWins: number;
  monthlyWinstreak: number;
  monthlyXp: number;
  solo: BedWarsSoloStats;
  wins: number;
  winstreak: number;
  weeklyBedsBroken: number;
  weeklyFinalKills: number;
  weeklyKills: number;
  weeklyLevel: number;
  weeklyWins: number;
  weeklyWinstreak: number;
  weeklyXp: number;
  xp: number;
}

export class BedWarsStats {
  constructor(data: Partial<APIPlayerBedWarsStats> = {}) {
    this.assists = data.assists ?? 0;
    this.bedsBroken = data.beds_broken ?? 0;
    this.dailyBedsBroken = data.beds_broken_daily ?? 0;
    this.weeklyBedsBroken = data.beds_broken_weekly ?? 0;
    this.monthlyBedsBroken = data.beds_broken_monthly ?? 0;
    this.bedsLost = data.beds_lost ?? 0;
    this.deaths = data.deaths ?? 0;
    this.finalAssists = data.final_assists ?? 0;
    this.finalDeaths = data.final_deaths ?? 0;
    this.finalKills = data.final_kills ?? 0;
    this.dailyFinalKills = data.final_kills_daily ?? 0;
    this.weeklyFinalKills = data.final_kills_weekly ?? 0;
    this.monthlyFinalKills = data.final_kills_monthly ?? 0;
    this.fkdr = data.fkdr ?? 0;
    this.gamesPlayed = data.games_played ?? 0;
    this.kills = data.kills ?? 0;
    this.dailyKills = data.kills_daily ?? 0;
    this.weeklyKills = data.kills_weekly ?? 0;
    this.monthlyKills = data.kills_monthly ?? 0;
    this.level = data.level ?? 0;
    this.levelBadge = new LevelBadge(
      data.level_badge ?? DefaultGameLevelBadgeColorType,
    );
    this.dailyLevel = data.level_daily ?? 0;
    this.weeklyLevel = data.level_weekly ?? 0;
    this.monthlyLevel = data.level_monthly ?? 0;
    this.losses = data.losses ?? 0;
    this.maxWinstreak = data.max_winstreak ?? 0;
    this.wins = data.wins ?? 0;
    this.dailyWins = data.wins_daily ?? 0;
    this.weeklyWins = data.wins_weekly ?? 0;
    this.monthlyWins = data.wins_monthly ?? 0;
    this.winstreak = data.winstreak ?? 0;
    this.dailyWinstreak = data.winstreak_daily ?? 0;
    this.weeklyWinstreak = data.winstreak_weekly ?? 0;
    this.monthlyWinstreak = data.winstreak_monthly ?? 0;
    this.xp = data.xp ?? 0;
    this.dailyXp = data.xp_daily ?? 0;
    this.weeklyXp = data.xp_weekly ?? 0;
    this.monthlyXp = data.xp_monthly ?? 0;

    this["1v1"] = new BedWars1v1Stats(data);
    this["2v2"] = new BedWars2v2Stats(data);
    this["3v3"] = new BedWars3v3Stats(data);
    this["3v3v3v3"] = new BedWars3v3v3v3Stats(data);
    this["4s"] = new BedWars4sStats(data);
    this["4v4"] = new BedWars4v4Stats(data);
    this["4v4v4v4"] = new BedWars4v4v4v4Stats(data);

    this.boostDoubles = new BedWarsBoostDoublesStats(data);
    this.boostSolo = new BedWarsBoostSoloStats(data);
    this.champions = new BedWarsChampionsStats(data);
    this.classicSolo = new BedWarsClassicSoloStats(data);
    this.doubles = new BedWarsDoublesStats(data);
    this.hardcore4v4v4v4 = new BedWarsHardcore4v4v4v4Stats(data);
    this.hardcoreSolo = new BedWarsHardcoreSoloStats(data);
    this.hookDoubles = new BedWarsHookDoublesStats(data);
    this.hookSolo = new BedWarsHookSoloStats(data);
    this.infectionDoubles = new BedWarsInfectionDoublesStats(data);
    this.infectionSolo = new BedWarsInfectionSoloStats(data);
    this.mega = new BedWarsMegaStats(data);
    this.solo = new BedWarsSoloStats(data);
  }
}
